### ISSUE TITLE
modificare padding credits superiore e mappa superiore in home

### ISSUE THREAD

**Issue by giuragu** [proloco-projato/mappiamolabellezza#56]
Non mi prende i padding di projato.css
Sembrerebbero corretti ma non vanno....

**Comment by aborruso** [comment]
ma in che senso non vanno? Ho aperto credits e il div "credits" dista 50px come da CSS.

Non deve essere così??

**Comment by giuragu** [comment]
@aborruso niente. Mi sono sbagliato io. La cache mi avrà tratto in inganno. Effettivamente è tutto ok.
Grazie comunque per avermelo fatto notare. Chiudo la issue
