### ISSUE TITLE
Audio tutorial

### ISSUE THREAD

**Issue by mariaserena95** [proloco-projato/mappiamolabellezza#58]

**Comment by giuragu** [comment]
caricare quello creato per il contest sugli altri form

**Comment by mariaserena95** [comment]
Caricare cosa?

Il giorno ven 24 apr 2020 alle 08:03 Giuseppe Ragusa <
notifications@github.com> ha scritto:

**Comment by giuragu** [comment]
Hai ragione @mariaserena95. Sono stato poco chiaro. Ho creato un tutorial audio/video per indicare come individuare latitudine e longitudine da riportare nei moduli raccolta foto e video.
Caricare intendevo appunto tutorial da inserire nei moduli per raccogliere foto e video....

**Comment by giuragu** [comment]
Chiudo issue perché ho appena provveduto...

**Comment by mariaserena95** [comment]
Ok va bene

Il giorno ven 24 apr 2020 alle 12:23 Giuseppe Ragusa <
notifications@github.com> ha scritto:

**Comment by giuragu** [comment]
@mariaserena95 grazie per la tua attenzione. Continua così...
